server:
  type: simple
  applicationContextPath: /application
  adminContextPath: /admin
  connector:
    type: http
    port: 9090
  # access logging
  requestLog:
    timeZone: UTC
    appenders:
      - type: file
        currentLogFilename: ./log/access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: ./log/access-%d.log
        archivedFileCount: 5

database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: "jdbc:h2:./myapplication;MV_STORE=FALSE;MVCC=FALSE"
  properties:
    validationQuery: "/* MyService Health Check */ SELECT 1"
    charSet: UTF-8

    # the minimum number of connections to keep open
    minSize: 8

    # the maximum number of connections to keep open
    maxSize: 32

    # whether or not idle connections should be validated
    checkConnectionWhileIdle: false

    # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
    evictionInterval: 10s

    # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
    minIdleTime: 1 minute

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: ./log/application.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: ./log/application-%d.log
      archivedFileCount: 5
      timeZone: UTC
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
